version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - './cmAppData/config:/config'
    ports:
      - "${CM_WEB-8085}:8085"

  cache:
    image: 'redis:7-alpine'

  database:
    image: 'mariadb:10.9.3'
    environment:
      MYSQL_ROOT_PASSWORD: CHANGE_THIS
      MYSQL_USER: cmuser
      MYSQL_PASSWORD: CHANGE_THIS
      MYSQL_DATABASE: ContextMod
    volumes:
      - './cmAppData/db:/var/lib/mysql'

  influx:
    image: 'influxdb:latest'
    volumes:
      - './cmAppData/influx:/var/lib/influxdb2'
    ports:
      - "${INFLUX_WEB:-8086}:8086"
    profiles:
      - full

  grafana:
    image: 'grafana/grafana'
    volumes:
      - './cmAppData/grafana:/var/lib/grafana'
    ports:
      - "${GRAFANA_WEB:-3000}:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: CHANGE_THIS
    depends_on:
      - influx
    profiles:
      - full
