operator:
  name: CHANGE_THIS #YOUR REDDIT USERNAME HERE
logging:
  # default level for all transports
  level: debug
  file:
    # override default level
    level: warn
    # true -> log folder at projectDir/log
    dirname: true
caching:
  provider:
    store: redis
    host: cache
    port: 6379
    prefix: prod
databaseConfig:
  migrations:
    continueOnAutomatedBackup: true
    #force: true # uncomment this to make cm run new migrations without confirmation
  #logging: ['query', 'error', 'warn', 'log'] # uncomment this to get typeorm to log EVERYTHING
  connection:
    type: 'mariadb'
    host: 'database'
    username: 'cmuser'
    # This should match the password set in docker-compose.yaml
    password: 'CHANGE_THIS'
    database: 'ContextMod'
web:
  credentials:
    redirectUri: 'http://localhost:8085/callback'
  session:
    storage: cache
  port: 8085
#
# Influx/Grafana requires additional configuration. See https://github.com/FoxxMD/context-mod/blob/master/docs/operator/database.md#influx
#
#influxConfig:
#  credentials:
#    url: 'http://influx:8086'
#    token: 'YourInfluxToken'
#    org: YourInfluxOrg
#    bucket: contextmod
