{
 "title": "ContextMod",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "bucket", "label": "Influx Bucket", "query": "buckets()" },
   {
    "name": "bot",
    "label": "Bots",
    "query": "from(bucket: \"${bucket}\")\n  |> range(start: -5m, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apiHealth\")\n  |> filter(fn: (r) => r[\"_field\"] == \"remaining\")\n  |> keep(columns: [\"bot\"])\n  |> distinct(column: \"bot\")\n  |> keep(columns: [\"_value\"])\n  |> yield(name: \"name\")"
   },
   {
    "name": "subreddit",
    "label": "Subreddits",
    "query": "  from(bucket: \"${bucket}\")\n  |> range(start: -12h, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"event\")\n  |> filter(fn: (r) => r[\"_field\"] == \"eventId\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/)\n  |> keep(columns: [\"subreddit\"])\n  |> distinct(column: \"subreddit\")\n  |> keep(columns: [\"_value\"])\n  |> yield(name: \"name\")"
   }
  ]
 },
 "panels": [
  { "title": "By The Numbers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Events (Triggered)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Total" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"event\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"eventId\")\n  |> group()\n  |> count()\n  |> yield(name: \"Total\")"
    },
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"event\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"eventId\" and r[\"triggered\"] == \"1\")\n  |> group()\n  |> count()\n  |> yield(name: \"Total\")"
    }
   ]
  },
  {
   "title": "Events By Source",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"event\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"eventId\")\n  |> group(columns: [\"sourceIdentifier\"])\n  |> count()\n  |> group()\n  |> keep(columns: [\"sourceIdentifier\",\"_value\"])"
    }
   ]
  },
  {
   "title": "Average Total API Quota Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apiHealth\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"used\")\n  |> aggregateWindow(every: 10m, fn: sum)\n  |> mean()\n  |> group(columns: [\"bot\"])\n  |> group()\n  |> keep(columns: [\"table\",\"_value\",\"_start\",\"_stop\",\"_time\",\"bot\"])"
    }
   ]
  },
  {
   "title": "Total API Calls",
   "type": "stat",
   "gridPos": { "h": 16, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apiHealth\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"used\")\n  |> aggregateWindow(every: 10m, fn: sum)\n  |> keep(columns: [\"_value\"])"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "/sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"event\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"eventId\")\n  |> group()\n  |> aggregateWindow(every: 1m, fn: count)\n  |> toFloat()\n  |> map(fn: (r) => ({r with _value: r._value / 60.0 }))\n  |> mean()\n  |> yield(name: \"Total\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"event\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"eventId\" and r[\"triggered\"] == \"1\")\n  |> group()\n  |> aggregateWindow(every: 1m, fn: count)\n  |> toFloat()\n  |> map(fn: (r) => ({r with _value: r._value / 60.0 }))\n  |> mean()\n  |> yield(name: \"Total\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "/min" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"event\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"eventId\")\n  |> group()\n  |> aggregateWindow(every: 60s, fn: count)\n  |> mean()\n  |> yield(name: \"Total\")"
    },
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"event\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"eventId\" and r[\"triggered\"] == \"1\")\n  |> group()\n  |> aggregateWindow(every: 60s, fn: count)\n  |> mean()\n  |> yield(name: \"Total\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "/hour" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"event\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"eventId\")\n  |> group()\n  |> aggregateWindow(every: 1h, fn: count)\n  |> mean()\n  |> yield(name: \"Total\")"
    },
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"event\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"eventId\" and r[\"triggered\"] == \"1\")\n  |> group()\n  |> aggregateWindow(every: 1h, fn: count)\n  |> mean()\n  |> yield(name: \"Total\")"
    }
   ]
  },
  {
   "title": "Events By Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"event\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"eventId\")\n  |> group(columns: [\"activityType\"])\n  |> count()\n  |> group()\n  |> keep(columns: [\"activityType\",\"_value\"])"
    }
   ]
  },
  {
   "title": "Total API Calls",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apiHealth\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"used\")\n  |> sum()\n  |> group(columns: [\"bot\"])\n  |> group()\n  |> map(fn: (r) => ({Bot: r.bot, Calls: r._value}))"
    }
   ]
  },
  {
   "title": "Avg Processing Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"event\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"processingTime\")\n  |> mean()\n  |> yield(name: \"Total\")"
    }
   ]
  },
  {
   "title": "Avg Queued Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"event\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"queuedTime\")\n  |> mean()\n  |> yield(name: \"Total\")"
    }
   ]
  },
  {
   "title": "Active Subreddits",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "  from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"event\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"eventId\")\n  |> group(columns: [\"subreddit\"])\n  |> keep(columns: [\"subreddit\"])\n  |> distinct(column: \"subreddit\")\n  |> count()\n  |> map(fn: (r) => ({_value: r.subreddit}))"
    }
   ]
  },
  {
   "title": "Active Bots",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apiHealth\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"remaining\")\n  |> keep(columns: [\"bot\"])\n  |> distinct(column: \"bot\")\n  |> keep(columns: [\"_value\"])\n  |> yield(name: \"name\")"
    }
   ]
  },
  { "title": "Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "API Usage Per Bot",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"apiHealth\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"remaining\")\n  |> group(columns: [\"bot\"])\n  |> map(fn: (r) => ({r with _value: 600 - r._value}))\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\n  |> keep(columns: [\"table\",\"_value\",\"_start\",\"_stop\",\"_time\",\"bot\"])"
    }
   ]
  },
  {
   "title": "Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"event\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"eventId\")\n  |> group(columns: [\"eventId\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: count)\n  |> yield(name: \"totalPerSub\")"
    },
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"event\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"eventId\" and r[\"triggered\"] == \"1\")\n  |> group(columns: [\"eventId\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: count)\n  |> yield(name: \"Total\")"
    }
   ]
  },
  {
   "title": "Events per Subreddit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"event\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"eventId\")\n  |> group(columns: [\"eventId\", \"subreddit\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: count)\n  |> yield(name: \"totalPerSub\")"
    }
   ]
  },
  {
   "title": "Triggered Events per Subreddit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"event\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r[\"_field\"] == \"eventId\" and r[\"triggered\"] == \"1\")\n  |> group(columns: [\"eventId\", \"subreddit\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: count)\n  |> yield(name: \"totalPerSub\")"
    }
   ]
  },
  {
   "title": "Triggered Checks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"triggeredEntity\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r.entityType == \"check\" and r._field == \"name\")\n  |> map(fn: (r) => ({r with entName: r._value}))\n  |> group(columns: [\"entName\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: count)"
    }
   ]
  },
  {
   "title": "Triggered Rules",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"triggeredEntity\")\n  |> filter(fn: (r) => r[\"bot\"] =~ /${bot:regex}/ and r[\"subereddit\"] =~ /${subreddit:regex}/)\n  |> filter(fn: (r) => r.entityType == \"rule\" and r._field == \"name\")\n  |> map(fn: (r) => ({r with entName: r._value}))\n  |> group(columns: [\"entName\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: count)"
    }
   ]
  }
 ]
}