import { MigrationInterface, QueryRunner } from "typeorm";

export class init1642180264563 implements MigrationInterface {
    name = 'init1642180264563'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "ActionType" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(200) NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "Author" ("id" varchar(20), "name" varchar(200) PRIMARY KEY NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "FilterResult" ("id" varchar(20) PRIMARY KEY NOT NULL, "join" varchar(200) NOT NULL, "passed" boolean NOT NULL, "type" varchar NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_d859426c8ed19b1a6a89c2a3e8" ON "FilterResult" ("type") `);
        await queryRunner.query(`CREATE TABLE "FilterCriteriaResult" ("id" varchar(20) PRIMARY KEY NOT NULL, "behavior" varchar(20) NOT NULL, "propertyResults" text NOT NULL, "passed" boolean NOT NULL, "type" varchar NOT NULL, "filterResultId" varchar(20), "criteriaId" varchar(20))`);
        await queryRunner.query(`CREATE INDEX "IDX_4cec0381d1eb9dedaf3ad68b56" ON "FilterCriteriaResult" ("type") `);
        await queryRunner.query(`CREATE TABLE "FilterCriteria" ("id" varchar(20) PRIMARY KEY NOT NULL, "criteria" text NOT NULL, "hash" varchar(300) NOT NULL, "type" varchar NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_62bbc6b414a9b54b8c16cbaf72" ON "FilterCriteria" ("type") `);
        await queryRunner.query(`CREATE TABLE "RuleType" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(200) NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "Rule" ("id" varchar(300) PRIMARY KEY NOT NULL, "name" varchar(300), "kindId" integer, "managerId" varchar(20))`);
        await queryRunner.query(`CREATE TABLE "RulePremise" ("ruleId" varchar NOT NULL, "configHash" varchar(300) NOT NULL, "config" text NOT NULL, "version" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), PRIMARY KEY ("ruleId", "configHash"))`);
        await queryRunner.query(`CREATE TABLE "RuleResult" ("id" varchar(20) PRIMARY KEY NOT NULL, "createdAt" integer NOT NULL, "triggered" boolean, "result" text, "fromCache" boolean, "data" text, "premiseRuleId" varchar, "premiseConfigHash" varchar(300), "checkResultId" varchar(20), "itemIs" varchar(20), "authorIs" varchar(20), CONSTRAINT "REL_d7fcca9682f7bcbb351f52f1b8" UNIQUE ("itemIs"), CONSTRAINT "REL_6663c0489c4b25c87e10695197" UNIQUE ("authorIs"))`);
        await queryRunner.query(`CREATE TABLE "ActionPremise" ("actionId" varchar NOT NULL, "config" text NOT NULL, "configHash" varchar(300) NOT NULL, "version" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), PRIMARY KEY ("actionId", "configHash"))`);
        await queryRunner.query(`CREATE TABLE "ActionResult" ("id" varchar(20) PRIMARY KEY NOT NULL, "createdAt" integer NOT NULL, "run" boolean NOT NULL, "dryRun" boolean NOT NULL, "success" boolean NOT NULL, "runReason" text, "result" text, "itemIs" varchar(20), "authorIs" varchar(20), "checkResultId" varchar(20), "premiseActionId" varchar, "premiseConfigHash" varchar(300), CONSTRAINT "REL_1a63301452c394f67093b473b2" UNIQUE ("itemIs"), CONSTRAINT "REL_1b857d089dc67957193851c7a6" UNIQUE ("authorIs"))`);
        await queryRunner.query(`CREATE TABLE "CheckResult" ("id" varchar(20) PRIMARY KEY NOT NULL, "createdAt" integer NOT NULL, "triggered" boolean NOT NULL, "fromCache" boolean, "condition" varchar(20) NOT NULL, "error" text, "postBehavior" varchar(50), "checkName" varchar(300), "runId" varchar(20), "itemIs" varchar(20), "authorIs" varchar(20), CONSTRAINT "REL_916eaa261805e5ea9d59a44dab" UNIQUE ("itemIs"), CONSTRAINT "REL_d7428bccbed07692b307e9da01" UNIQUE ("authorIs"))`);
        await queryRunner.query(`CREATE TABLE "Check" ("name" varchar(300) PRIMARY KEY NOT NULL, "type" varchar(20) NOT NULL, "runName" varchar(300), "managerId" varchar(20))`);
        await queryRunner.query(`CREATE TABLE "Run" ("name" varchar(300) PRIMARY KEY NOT NULL, "managerId" varchar(20))`);
        await queryRunner.query(`CREATE TABLE "RunResult" ("id" varchar(20) PRIMARY KEY NOT NULL, "createdAt" integer NOT NULL, "triggered" boolean NOT NULL, "reason" text, "error" text, "runName" varchar(300), "eventId" varchar(20), "itemIs" varchar(20), "authorIs" varchar(20), CONSTRAINT "REL_b78aa13f4c55941c2590c2e77a" UNIQUE ("itemIs"), CONSTRAINT "REL_939591dc45dc335e212db811f5" UNIQUE ("authorIs"))`);
        await queryRunner.query(`CREATE TABLE "ActivitySource" ("id" varchar(50) PRIMARY KEY NOT NULL, "type" varchar(30) NOT NULL, "identifier" varchar(100), "action" varchar(100), "delay" integer, "goto" varchar(100), "managerId" varchar(20))`);
        await queryRunner.query(`CREATE TABLE "CMEvent" ("id" varchar(20) PRIMARY KEY NOT NULL, "triggered" boolean NOT NULL, "queuedAt" integer NOT NULL, "processedAt" integer NOT NULL, "managerId" varchar(20), "activity_id" varchar, "sourceId" varchar(50))`);
        await queryRunner.query(`CREATE INDEX "IDX_1a2b070b8e5a31b4e041338645" ON "CMEvent" ("queuedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_04380a477fa96ef4f0935a1224" ON "CMEvent" ("processedAt") `);
        await queryRunner.query(`CREATE TABLE "Activity" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "type" varchar(20) NOT NULL, "content" text NOT NULL, "permalink" text NOT NULL, "subredditId" varchar, "authorName" varchar(200), "submission_id" varchar)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_299b1e2f9643fd7670370b726f" ON "Activity" ("permalink") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fab3ccdf4e40a98708e2fa7380" ON "Activity" ("name", "type") `);
        await queryRunner.query(`CREATE TABLE "Subreddit" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(200) NOT NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_006cd1e68c2aac42e763dba332" ON "Subreddit" ("name") `);
        await queryRunner.query(`CREATE TABLE "Bot" ("id" varchar(20) PRIMARY KEY NOT NULL, "name" varchar(200) NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "Manager" ("id" varchar(20) PRIMARY KEY NOT NULL, "name" varchar(200) NOT NULL, "botId" varchar(20), "subredditId" varchar)`);
        await queryRunner.query(`CREATE TABLE "Action" ("id" varchar(300) PRIMARY KEY NOT NULL, "name" varchar(300), "kindId" integer, "managerId" varchar(20))`);
        await queryRunner.query(`CREATE TABLE "DispatchedAction" ("id" varchar(20) PRIMARY KEY NOT NULL, "createdAt" integer NOT NULL, "activityId" varchar NOT NULL, "delay" integer NOT NULL, "action" varchar, "goto" varchar(200), "type" varchar NOT NULL, "identifier" varchar(200), "cancelIfQueued" varchar(200), "onExistingFound" varchar, "tardyTolerant" varchar(200) NOT NULL, "managerId" varchar(20))`);
        await queryRunner.query(`CREATE TABLE "TimeSeriesStat" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" integer NOT NULL, "granularity" varchar NOT NULL, "metric" varchar(60) NOT NULL, "value" bigint NOT NULL, "managerId" varchar NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_842bf2abc463b163fdd4406031" ON "TimeSeriesStat" ("createdAt") `);
        await queryRunner.query(`CREATE TABLE "TotalStat" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" integer NOT NULL, "metric" varchar(60) NOT NULL, "value" bigint NOT NULL, "managerId" varchar NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "IDX_99faa3b1f539a14f095192a127" ON "TotalStat" ("createdAt") `);
        await queryRunner.query(`DROP INDEX "IDX_4cec0381d1eb9dedaf3ad68b56"`);
        await queryRunner.query(`CREATE TABLE "temporary_FilterCriteriaResult" ("id" varchar(20) PRIMARY KEY NOT NULL, "behavior" varchar(20) NOT NULL, "propertyResults" text NOT NULL, "passed" boolean NOT NULL, "type" varchar NOT NULL, "filterResultId" varchar(20), "criteriaId" varchar(20), CONSTRAINT "FK_dc19c7594354a1657b7df9112ec" FOREIGN KEY ("filterResultId") REFERENCES "FilterResult" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_8c43758c3347b6b5446fc329ec5" FOREIGN KEY ("criteriaId") REFERENCES "FilterCriteria" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_FilterCriteriaResult"("id", "behavior", "propertyResults", "passed", "type", "filterResultId", "criteriaId") SELECT "id", "behavior", "propertyResults", "passed", "type", "filterResultId", "criteriaId" FROM "FilterCriteriaResult"`);
        await queryRunner.query(`DROP TABLE "FilterCriteriaResult"`);
        await queryRunner.query(`ALTER TABLE "temporary_FilterCriteriaResult" RENAME TO "FilterCriteriaResult"`);
        await queryRunner.query(`CREATE INDEX "IDX_4cec0381d1eb9dedaf3ad68b56" ON "FilterCriteriaResult" ("type") `);
        await queryRunner.query(`CREATE TABLE "temporary_Rule" ("id" varchar(300) PRIMARY KEY NOT NULL, "name" varchar(300), "kindId" integer, "managerId" varchar(20), CONSTRAINT "FK_4a5badf817f15cec72666747ab0" FOREIGN KEY ("kindId") REFERENCES "RuleType" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_1c00ce042d711769ac0a3ed050d" FOREIGN KEY ("managerId") REFERENCES "Manager" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_Rule"("id", "name", "kindId", "managerId") SELECT "id", "name", "kindId", "managerId" FROM "Rule"`);
        await queryRunner.query(`DROP TABLE "Rule"`);
        await queryRunner.query(`ALTER TABLE "temporary_Rule" RENAME TO "Rule"`);
        await queryRunner.query(`CREATE TABLE "temporary_RulePremise" ("ruleId" varchar NOT NULL, "configHash" varchar(300) NOT NULL, "config" text NOT NULL, "version" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_f51038405373230f5a27965b56b" FOREIGN KEY ("ruleId") REFERENCES "Rule" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("ruleId", "configHash"))`);
        await queryRunner.query(`INSERT INTO "temporary_RulePremise"("ruleId", "configHash", "config", "version", "createdAt", "updatedAt") SELECT "ruleId", "configHash", "config", "version", "createdAt", "updatedAt" FROM "RulePremise"`);
        await queryRunner.query(`DROP TABLE "RulePremise"`);
        await queryRunner.query(`ALTER TABLE "temporary_RulePremise" RENAME TO "RulePremise"`);
        await queryRunner.query(`CREATE TABLE "temporary_RuleResult" ("id" varchar(20) PRIMARY KEY NOT NULL, "createdAt" integer NOT NULL, "triggered" boolean, "result" text, "fromCache" boolean, "data" text, "premiseRuleId" varchar, "premiseConfigHash" varchar(300), "checkResultId" varchar(20), "itemIs" varchar(20), "authorIs" varchar(20), CONSTRAINT "REL_d7fcca9682f7bcbb351f52f1b8" UNIQUE ("itemIs"), CONSTRAINT "REL_6663c0489c4b25c87e10695197" UNIQUE ("authorIs"), CONSTRAINT "FK_efabb62c41dedee55d5ed6de012" FOREIGN KEY ("premiseRuleId", "premiseConfigHash") REFERENCES "RulePremise" ("ruleId", "configHash") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_1e9f8b869ba5e4f6539ec2982e7" FOREIGN KEY ("checkResultId") REFERENCES "CheckResult" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_d7fcca9682f7bcbb351f52f1b8a" FOREIGN KEY ("itemIs") REFERENCES "FilterResult" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_6663c0489c4b25c87e106951970" FOREIGN KEY ("authorIs") REFERENCES "FilterResult" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_RuleResult"("id", "createdAt", "triggered", "result", "fromCache", "data", "premiseRuleId", "premiseConfigHash", "checkResultId", "itemIs", "authorIs") SELECT "id", "createdAt", "triggered", "result", "fromCache", "data", "premiseRuleId", "premiseConfigHash", "checkResultId", "itemIs", "authorIs" FROM "RuleResult"`);
        await queryRunner.query(`DROP TABLE "RuleResult"`);
        await queryRunner.query(`ALTER TABLE "temporary_RuleResult" RENAME TO "RuleResult"`);
        await queryRunner.query(`CREATE TABLE "temporary_ActionPremise" ("actionId" varchar NOT NULL, "config" text NOT NULL, "configHash" varchar(300) NOT NULL, "version" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_3238bce2b637c0bd75aaa3062ed" FOREIGN KEY ("actionId") REFERENCES "Action" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("actionId", "configHash"))`);
        await queryRunner.query(`INSERT INTO "temporary_ActionPremise"("actionId", "config", "configHash", "version", "createdAt", "updatedAt") SELECT "actionId", "config", "configHash", "version", "createdAt", "updatedAt" FROM "ActionPremise"`);
        await queryRunner.query(`DROP TABLE "ActionPremise"`);
        await queryRunner.query(`ALTER TABLE "temporary_ActionPremise" RENAME TO "ActionPremise"`);
        await queryRunner.query(`CREATE TABLE "temporary_ActionResult" ("id" varchar(20) PRIMARY KEY NOT NULL, "createdAt" integer NOT NULL, "run" boolean NOT NULL, "dryRun" boolean NOT NULL, "success" boolean NOT NULL, "runReason" text, "result" text, "itemIs" varchar(20), "authorIs" varchar(20), "checkResultId" varchar(20), "premiseActionId" varchar, "premiseConfigHash" varchar(300), CONSTRAINT "REL_1a63301452c394f67093b473b2" UNIQUE ("itemIs"), CONSTRAINT "REL_1b857d089dc67957193851c7a6" UNIQUE ("authorIs"), CONSTRAINT "FK_1a63301452c394f67093b473b22" FOREIGN KEY ("itemIs") REFERENCES "FilterResult" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_1b857d089dc67957193851c7a69" FOREIGN KEY ("authorIs") REFERENCES "FilterResult" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_2d60cacb52ea5730749b5587f09" FOREIGN KEY ("checkResultId") REFERENCES "CheckResult" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_a90ca89fca26998e3fa09a23c8d" FOREIGN KEY ("premiseActionId", "premiseConfigHash") REFERENCES "ActionPremise" ("actionId", "configHash") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_ActionResult"("id", "createdAt", "run", "dryRun", "success", "runReason", "result", "itemIs", "authorIs", "checkResultId", "premiseActionId", "premiseConfigHash") SELECT "id", "createdAt", "run", "dryRun", "success", "runReason", "result", "itemIs", "authorIs", "checkResultId", "premiseActionId", "premiseConfigHash" FROM "ActionResult"`);
        await queryRunner.query(`DROP TABLE "ActionResult"`);
        await queryRunner.query(`ALTER TABLE "temporary_ActionResult" RENAME TO "ActionResult"`);
        await queryRunner.query(`CREATE TABLE "temporary_CheckResult" ("id" varchar(20) PRIMARY KEY NOT NULL, "createdAt" integer NOT NULL, "triggered" boolean NOT NULL, "fromCache" boolean, "condition" varchar(20) NOT NULL, "error" text, "postBehavior" varchar(50), "checkName" varchar(300), "runId" varchar(20), "itemIs" varchar(20), "authorIs" varchar(20), CONSTRAINT "REL_916eaa261805e5ea9d59a44dab" UNIQUE ("itemIs"), CONSTRAINT "REL_d7428bccbed07692b307e9da01" UNIQUE ("authorIs"), CONSTRAINT "FK_80e6eeb7f0d8cf3dc0e17c9b243" FOREIGN KEY ("checkName") REFERENCES "Check" ("name") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_494d26de4c4d3cfa49c3f3593f9" FOREIGN KEY ("runId") REFERENCES "RunResult" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_916eaa261805e5ea9d59a44dab0" FOREIGN KEY ("itemIs") REFERENCES "FilterResult" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_d7428bccbed07692b307e9da012" FOREIGN KEY ("authorIs") REFERENCES "FilterResult" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_CheckResult"("id", "createdAt", "triggered", "fromCache", "condition", "error", "postBehavior", "checkName", "runId", "itemIs", "authorIs") SELECT "id", "createdAt", "triggered", "fromCache", "condition", "error", "postBehavior", "checkName", "runId", "itemIs", "authorIs" FROM "CheckResult"`);
        await queryRunner.query(`DROP TABLE "CheckResult"`);
        await queryRunner.query(`ALTER TABLE "temporary_CheckResult" RENAME TO "CheckResult"`);
        await queryRunner.query(`CREATE TABLE "temporary_Check" ("name" varchar(300) PRIMARY KEY NOT NULL, "type" varchar(20) NOT NULL, "runName" varchar(300), "managerId" varchar(20), CONSTRAINT "FK_2ba1ca3521dcbaa28d59a04170d" FOREIGN KEY ("runName") REFERENCES "Run" ("name") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_a448e5cdfd039d58f0c8c342154" FOREIGN KEY ("managerId") REFERENCES "Manager" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_Check"("name", "type", "runName", "managerId") SELECT "name", "type", "runName", "managerId" FROM "Check"`);
        await queryRunner.query(`DROP TABLE "Check"`);
        await queryRunner.query(`ALTER TABLE "temporary_Check" RENAME TO "Check"`);
        await queryRunner.query(`CREATE TABLE "temporary_Run" ("name" varchar(300) PRIMARY KEY NOT NULL, "managerId" varchar(20), CONSTRAINT "FK_7cc1eefde3bad0694569dad6f4b" FOREIGN KEY ("managerId") REFERENCES "Manager" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_Run"("name", "managerId") SELECT "name", "managerId" FROM "Run"`);
        await queryRunner.query(`DROP TABLE "Run"`);
        await queryRunner.query(`ALTER TABLE "temporary_Run" RENAME TO "Run"`);
        await queryRunner.query(`CREATE TABLE "temporary_RunResult" ("id" varchar(20) PRIMARY KEY NOT NULL, "createdAt" integer NOT NULL, "triggered" boolean NOT NULL, "reason" text, "error" text, "runName" varchar(300), "eventId" varchar(20), "itemIs" varchar(20), "authorIs" varchar(20), CONSTRAINT "REL_b78aa13f4c55941c2590c2e77a" UNIQUE ("itemIs"), CONSTRAINT "REL_939591dc45dc335e212db811f5" UNIQUE ("authorIs"), CONSTRAINT "FK_4192a6d00356952feb79c3c440a" FOREIGN KEY ("runName") REFERENCES "Run" ("name") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_7e68ae33f1bccd3edc7b71e1889" FOREIGN KEY ("eventId") REFERENCES "CMEvent" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_b78aa13f4c55941c2590c2e77a4" FOREIGN KEY ("itemIs") REFERENCES "FilterResult" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_939591dc45dc335e212db811f5f" FOREIGN KEY ("authorIs") REFERENCES "FilterResult" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_RunResult"("id", "createdAt", "triggered", "reason", "error", "runName", "eventId", "itemIs", "authorIs") SELECT "id", "createdAt", "triggered", "reason", "error", "runName", "eventId", "itemIs", "authorIs" FROM "RunResult"`);
        await queryRunner.query(`DROP TABLE "RunResult"`);
        await queryRunner.query(`ALTER TABLE "temporary_RunResult" RENAME TO "RunResult"`);
        await queryRunner.query(`CREATE TABLE "temporary_ActivitySource" ("id" varchar(50) PRIMARY KEY NOT NULL, "type" varchar(30) NOT NULL, "identifier" varchar(100), "action" varchar(100), "delay" integer, "goto" varchar(100), "managerId" varchar(20), CONSTRAINT "FK_377f3bf62e4c25db9535b310b98" FOREIGN KEY ("managerId") REFERENCES "Manager" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_ActivitySource"("id", "type", "identifier", "action", "delay", "goto", "managerId") SELECT "id", "type", "identifier", "action", "delay", "goto", "managerId" FROM "ActivitySource"`);
        await queryRunner.query(`DROP TABLE "ActivitySource"`);
        await queryRunner.query(`ALTER TABLE "temporary_ActivitySource" RENAME TO "ActivitySource"`);
        await queryRunner.query(`DROP INDEX "IDX_1a2b070b8e5a31b4e041338645"`);
        await queryRunner.query(`DROP INDEX "IDX_04380a477fa96ef4f0935a1224"`);
        await queryRunner.query(`CREATE TABLE "temporary_CMEvent" ("id" varchar(20) PRIMARY KEY NOT NULL, "triggered" boolean NOT NULL, "queuedAt" integer NOT NULL, "processedAt" integer NOT NULL, "managerId" varchar(20), "activity_id" varchar, "sourceId" varchar(50), CONSTRAINT "FK_783b7756d43d913669c82571413" FOREIGN KEY ("managerId") REFERENCES "Manager" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_3d34e6da295fe19526f38719979" FOREIGN KEY ("activity_id") REFERENCES "Activity" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_0ad0162a213db1abb9e6b8dba79" FOREIGN KEY ("sourceId") REFERENCES "ActivitySource" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_CMEvent"("id", "triggered", "queuedAt", "processedAt", "managerId", "activity_id", "sourceId") SELECT "id", "triggered", "queuedAt", "processedAt", "managerId", "activity_id", "sourceId" FROM "CMEvent"`);
        await queryRunner.query(`DROP TABLE "CMEvent"`);
        await queryRunner.query(`ALTER TABLE "temporary_CMEvent" RENAME TO "CMEvent"`);
        await queryRunner.query(`CREATE INDEX "IDX_1a2b070b8e5a31b4e041338645" ON "CMEvent" ("queuedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_04380a477fa96ef4f0935a1224" ON "CMEvent" ("processedAt") `);
        await queryRunner.query(`DROP INDEX "IDX_299b1e2f9643fd7670370b726f"`);
        await queryRunner.query(`DROP INDEX "IDX_fab3ccdf4e40a98708e2fa7380"`);
        await queryRunner.query(`CREATE TABLE "temporary_Activity" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "type" varchar(20) NOT NULL, "content" text NOT NULL, "permalink" text NOT NULL, "subredditId" varchar, "authorName" varchar(200), "submission_id" varchar, CONSTRAINT "FK_2225f1b06b65334ec3b66864d66" FOREIGN KEY ("subredditId") REFERENCES "Subreddit" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_10fcfbf2415dd4019a2c3353228" FOREIGN KEY ("authorName") REFERENCES "Author" ("name") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_3ded3bc70aaa3073cb0cd5468f7" FOREIGN KEY ("submission_id") REFERENCES "Activity" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_Activity"("id", "name", "type", "content", "permalink", "subredditId", "authorName", "submission_id") SELECT "id", "name", "type", "content", "permalink", "subredditId", "authorName", "submission_id" FROM "Activity"`);
        await queryRunner.query(`DROP TABLE "Activity"`);
        await queryRunner.query(`ALTER TABLE "temporary_Activity" RENAME TO "Activity"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_299b1e2f9643fd7670370b726f" ON "Activity" ("permalink") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fab3ccdf4e40a98708e2fa7380" ON "Activity" ("name", "type") `);
        await queryRunner.query(`CREATE TABLE "temporary_Manager" ("id" varchar(20) PRIMARY KEY NOT NULL, "name" varchar(200) NOT NULL, "botId" varchar(20), "subredditId" varchar, CONSTRAINT "FK_006c7122c77aa3c9f13632469c0" FOREIGN KEY ("botId") REFERENCES "Bot" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_467929cdc981f0b480b5785d0b1" FOREIGN KEY ("subredditId") REFERENCES "Subreddit" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_Manager"("id", "name", "botId", "subredditId") SELECT "id", "name", "botId", "subredditId" FROM "Manager"`);
        await queryRunner.query(`DROP TABLE "Manager"`);
        await queryRunner.query(`ALTER TABLE "temporary_Manager" RENAME TO "Manager"`);
        await queryRunner.query(`CREATE TABLE "temporary_Action" ("id" varchar(300) PRIMARY KEY NOT NULL, "name" varchar(300), "kindId" integer, "managerId" varchar(20), CONSTRAINT "FK_f0e67cd8664632cdd80f8c203ab" FOREIGN KEY ("kindId") REFERENCES "ActionType" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_54610dbcb521e1ef1470ef52010" FOREIGN KEY ("managerId") REFERENCES "Manager" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_Action"("id", "name", "kindId", "managerId") SELECT "id", "name", "kindId", "managerId" FROM "Action"`);
        await queryRunner.query(`DROP TABLE "Action"`);
        await queryRunner.query(`ALTER TABLE "temporary_Action" RENAME TO "Action"`);
        await queryRunner.query(`CREATE TABLE "temporary_DispatchedAction" ("id" varchar(20) PRIMARY KEY NOT NULL, "createdAt" integer NOT NULL, "activityId" varchar NOT NULL, "delay" integer NOT NULL, "action" varchar, "goto" varchar(200), "type" varchar NOT NULL, "identifier" varchar(200), "cancelIfQueued" varchar(200), "onExistingFound" varchar, "tardyTolerant" varchar(200) NOT NULL, "managerId" varchar(20), CONSTRAINT "FK_ddffc78d76756587a3d1aa3f023" FOREIGN KEY ("managerId") REFERENCES "Manager" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_DispatchedAction"("id", "createdAt", "activityId", "delay", "action", "goto", "type", "identifier", "cancelIfQueued", "onExistingFound", "tardyTolerant", "managerId") SELECT "id", "createdAt", "activityId", "delay", "action", "goto", "type", "identifier", "cancelIfQueued", "onExistingFound", "tardyTolerant", "managerId" FROM "DispatchedAction"`);
        await queryRunner.query(`DROP TABLE "DispatchedAction"`);
        await queryRunner.query(`ALTER TABLE "temporary_DispatchedAction" RENAME TO "DispatchedAction"`);
        await queryRunner.query(`DROP INDEX "IDX_842bf2abc463b163fdd4406031"`);
        await queryRunner.query(`CREATE TABLE "temporary_TimeSeriesStat" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" integer NOT NULL, "granularity" varchar NOT NULL, "metric" varchar(60) NOT NULL, "value" bigint NOT NULL, "managerId" varchar NOT NULL, CONSTRAINT "FK_3304748d37b3b31ec30a0fbc6ed" FOREIGN KEY ("managerId") REFERENCES "Manager" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_TimeSeriesStat"("id", "createdAt", "granularity", "metric", "value", "managerId") SELECT "id", "createdAt", "granularity", "metric", "value", "managerId" FROM "TimeSeriesStat"`);
        await queryRunner.query(`DROP TABLE "TimeSeriesStat"`);
        await queryRunner.query(`ALTER TABLE "temporary_TimeSeriesStat" RENAME TO "TimeSeriesStat"`);
        await queryRunner.query(`CREATE INDEX "IDX_842bf2abc463b163fdd4406031" ON "TimeSeriesStat" ("createdAt") `);
        await queryRunner.query(`DROP INDEX "IDX_99faa3b1f539a14f095192a127"`);
        await queryRunner.query(`CREATE TABLE "temporary_TotalStat" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" integer NOT NULL, "metric" varchar(60) NOT NULL, "value" bigint NOT NULL, "managerId" varchar NOT NULL, CONSTRAINT "FK_59e9d2e2829119e2e4395b3bdde" FOREIGN KEY ("managerId") REFERENCES "Manager" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_TotalStat"("id", "createdAt", "metric", "value", "managerId") SELECT "id", "createdAt", "metric", "value", "managerId" FROM "TotalStat"`);
        await queryRunner.query(`DROP TABLE "TotalStat"`);
        await queryRunner.query(`ALTER TABLE "temporary_TotalStat" RENAME TO "TotalStat"`);
        await queryRunner.query(`CREATE INDEX "IDX_99faa3b1f539a14f095192a127" ON "TotalStat" ("createdAt") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_99faa3b1f539a14f095192a127"`);
        await queryRunner.query(`ALTER TABLE "TotalStat" RENAME TO "temporary_TotalStat"`);
        await queryRunner.query(`CREATE TABLE "TotalStat" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" integer NOT NULL, "metric" varchar(60) NOT NULL, "value" bigint NOT NULL, "managerId" varchar NOT NULL)`);
        await queryRunner.query(`INSERT INTO "TotalStat"("id", "createdAt", "metric", "value", "managerId") SELECT "id", "createdAt", "metric", "value", "managerId" FROM "temporary_TotalStat"`);
        await queryRunner.query(`DROP TABLE "temporary_TotalStat"`);
        await queryRunner.query(`CREATE INDEX "IDX_99faa3b1f539a14f095192a127" ON "TotalStat" ("createdAt") `);
        await queryRunner.query(`DROP INDEX "IDX_842bf2abc463b163fdd4406031"`);
        await queryRunner.query(`ALTER TABLE "TimeSeriesStat" RENAME TO "temporary_TimeSeriesStat"`);
        await queryRunner.query(`CREATE TABLE "TimeSeriesStat" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "createdAt" integer NOT NULL, "granularity" varchar NOT NULL, "metric" varchar(60) NOT NULL, "value" bigint NOT NULL, "managerId" varchar NOT NULL)`);
        await queryRunner.query(`INSERT INTO "TimeSeriesStat"("id", "createdAt", "granularity", "metric", "value", "managerId") SELECT "id", "createdAt", "granularity", "metric", "value", "managerId" FROM "temporary_TimeSeriesStat"`);
        await queryRunner.query(`DROP TABLE "temporary_TimeSeriesStat"`);
        await queryRunner.query(`CREATE INDEX "IDX_842bf2abc463b163fdd4406031" ON "TimeSeriesStat" ("createdAt") `);
        await queryRunner.query(`ALTER TABLE "DispatchedAction" RENAME TO "temporary_DispatchedAction"`);
        await queryRunner.query(`CREATE TABLE "DispatchedAction" ("id" varchar(20) PRIMARY KEY NOT NULL, "createdAt" integer NOT NULL, "activityId" varchar NOT NULL, "delay" integer NOT NULL, "action" varchar, "goto" varchar(200), "type" varchar NOT NULL, "identifier" varchar(200), "cancelIfQueued" varchar(200), "onExistingFound" varchar, "tardyTolerant" varchar(200) NOT NULL, "managerId" varchar(20))`);
        await queryRunner.query(`INSERT INTO "DispatchedAction"("id", "createdAt", "activityId", "delay", "action", "goto", "type", "identifier", "cancelIfQueued", "onExistingFound", "tardyTolerant", "managerId") SELECT "id", "createdAt", "activityId", "delay", "action", "goto", "type", "identifier", "cancelIfQueued", "onExistingFound", "tardyTolerant", "managerId" FROM "temporary_DispatchedAction"`);
        await queryRunner.query(`DROP TABLE "temporary_DispatchedAction"`);
        await queryRunner.query(`ALTER TABLE "Action" RENAME TO "temporary_Action"`);
        await queryRunner.query(`CREATE TABLE "Action" ("id" varchar(300) PRIMARY KEY NOT NULL, "name" varchar(300), "kindId" integer, "managerId" varchar(20))`);
        await queryRunner.query(`INSERT INTO "Action"("id", "name", "kindId", "managerId") SELECT "id", "name", "kindId", "managerId" FROM "temporary_Action"`);
        await queryRunner.query(`DROP TABLE "temporary_Action"`);
        await queryRunner.query(`ALTER TABLE "Manager" RENAME TO "temporary_Manager"`);
        await queryRunner.query(`CREATE TABLE "Manager" ("id" varchar(20) PRIMARY KEY NOT NULL, "name" varchar(200) NOT NULL, "botId" varchar(20), "subredditId" varchar)`);
        await queryRunner.query(`INSERT INTO "Manager"("id", "name", "botId", "subredditId") SELECT "id", "name", "botId", "subredditId" FROM "temporary_Manager"`);
        await queryRunner.query(`DROP TABLE "temporary_Manager"`);
        await queryRunner.query(`DROP INDEX "IDX_fab3ccdf4e40a98708e2fa7380"`);
        await queryRunner.query(`DROP INDEX "IDX_299b1e2f9643fd7670370b726f"`);
        await queryRunner.query(`ALTER TABLE "Activity" RENAME TO "temporary_Activity"`);
        await queryRunner.query(`CREATE TABLE "Activity" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "type" varchar(20) NOT NULL, "content" text NOT NULL, "permalink" text NOT NULL, "subredditId" varchar, "authorName" varchar(200), "submission_id" varchar)`);
        await queryRunner.query(`INSERT INTO "Activity"("id", "name", "type", "content", "permalink", "subredditId", "authorName", "submission_id") SELECT "id", "name", "type", "content", "permalink", "subredditId", "authorName", "submission_id" FROM "temporary_Activity"`);
        await queryRunner.query(`DROP TABLE "temporary_Activity"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fab3ccdf4e40a98708e2fa7380" ON "Activity" ("name", "type") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_299b1e2f9643fd7670370b726f" ON "Activity" ("permalink") `);
        await queryRunner.query(`DROP INDEX "IDX_04380a477fa96ef4f0935a1224"`);
        await queryRunner.query(`DROP INDEX "IDX_1a2b070b8e5a31b4e041338645"`);
        await queryRunner.query(`ALTER TABLE "CMEvent" RENAME TO "temporary_CMEvent"`);
        await queryRunner.query(`CREATE TABLE "CMEvent" ("id" varchar(20) PRIMARY KEY NOT NULL, "triggered" boolean NOT NULL, "queuedAt" integer NOT NULL, "processedAt" integer NOT NULL, "managerId" varchar(20), "activity_id" varchar, "sourceId" varchar(50))`);
        await queryRunner.query(`INSERT INTO "CMEvent"("id", "triggered", "queuedAt", "processedAt", "managerId", "activity_id", "sourceId") SELECT "id", "triggered", "queuedAt", "processedAt", "managerId", "activity_id", "sourceId" FROM "temporary_CMEvent"`);
        await queryRunner.query(`DROP TABLE "temporary_CMEvent"`);
        await queryRunner.query(`CREATE INDEX "IDX_04380a477fa96ef4f0935a1224" ON "CMEvent" ("processedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a2b070b8e5a31b4e041338645" ON "CMEvent" ("queuedAt") `);
        await queryRunner.query(`ALTER TABLE "ActivitySource" RENAME TO "temporary_ActivitySource"`);
        await queryRunner.query(`CREATE TABLE "ActivitySource" ("id" varchar(50) PRIMARY KEY NOT NULL, "type" varchar(30) NOT NULL, "identifier" varchar(100), "action" varchar(100), "delay" integer, "goto" varchar(100), "managerId" varchar(20))`);
        await queryRunner.query(`INSERT INTO "ActivitySource"("id", "type", "identifier", "action", "delay", "goto", "managerId") SELECT "id", "type", "identifier", "action", "delay", "goto", "managerId" FROM "temporary_ActivitySource"`);
        await queryRunner.query(`DROP TABLE "temporary_ActivitySource"`);
        await queryRunner.query(`ALTER TABLE "RunResult" RENAME TO "temporary_RunResult"`);
        await queryRunner.query(`CREATE TABLE "RunResult" ("id" varchar(20) PRIMARY KEY NOT NULL, "createdAt" integer NOT NULL, "triggered" boolean NOT NULL, "reason" text, "error" text, "runName" varchar(300), "eventId" varchar(20), "itemIs" varchar(20), "authorIs" varchar(20), CONSTRAINT "REL_b78aa13f4c55941c2590c2e77a" UNIQUE ("itemIs"), CONSTRAINT "REL_939591dc45dc335e212db811f5" UNIQUE ("authorIs"))`);
        await queryRunner.query(`INSERT INTO "RunResult"("id", "createdAt", "triggered", "reason", "error", "runName", "eventId", "itemIs", "authorIs") SELECT "id", "createdAt", "triggered", "reason", "error", "runName", "eventId", "itemIs", "authorIs" FROM "temporary_RunResult"`);
        await queryRunner.query(`DROP TABLE "temporary_RunResult"`);
        await queryRunner.query(`ALTER TABLE "Run" RENAME TO "temporary_Run"`);
        await queryRunner.query(`CREATE TABLE "Run" ("name" varchar(300) PRIMARY KEY NOT NULL, "managerId" varchar(20))`);
        await queryRunner.query(`INSERT INTO "Run"("name", "managerId") SELECT "name", "managerId" FROM "temporary_Run"`);
        await queryRunner.query(`DROP TABLE "temporary_Run"`);
        await queryRunner.query(`ALTER TABLE "Check" RENAME TO "temporary_Check"`);
        await queryRunner.query(`CREATE TABLE "Check" ("name" varchar(300) PRIMARY KEY NOT NULL, "type" varchar(20) NOT NULL, "runName" varchar(300), "managerId" varchar(20))`);
        await queryRunner.query(`INSERT INTO "Check"("name", "type", "runName", "managerId") SELECT "name", "type", "runName", "managerId" FROM "temporary_Check"`);
        await queryRunner.query(`DROP TABLE "temporary_Check"`);
        await queryRunner.query(`ALTER TABLE "CheckResult" RENAME TO "temporary_CheckResult"`);
        await queryRunner.query(`CREATE TABLE "CheckResult" ("id" varchar(20) PRIMARY KEY NOT NULL, "createdAt" integer NOT NULL, "triggered" boolean NOT NULL, "fromCache" boolean, "condition" varchar(20) NOT NULL, "error" text, "postBehavior" varchar(50), "checkName" varchar(300), "runId" varchar(20), "itemIs" varchar(20), "authorIs" varchar(20), CONSTRAINT "REL_916eaa261805e5ea9d59a44dab" UNIQUE ("itemIs"), CONSTRAINT "REL_d7428bccbed07692b307e9da01" UNIQUE ("authorIs"))`);
        await queryRunner.query(`INSERT INTO "CheckResult"("id", "createdAt", "triggered", "fromCache", "condition", "error", "postBehavior", "checkName", "runId", "itemIs", "authorIs") SELECT "id", "createdAt", "triggered", "fromCache", "condition", "error", "postBehavior", "checkName", "runId", "itemIs", "authorIs" FROM "temporary_CheckResult"`);
        await queryRunner.query(`DROP TABLE "temporary_CheckResult"`);
        await queryRunner.query(`ALTER TABLE "ActionResult" RENAME TO "temporary_ActionResult"`);
        await queryRunner.query(`CREATE TABLE "ActionResult" ("id" varchar(20) PRIMARY KEY NOT NULL, "createdAt" integer NOT NULL, "run" boolean NOT NULL, "dryRun" boolean NOT NULL, "success" boolean NOT NULL, "runReason" text, "result" text, "itemIs" varchar(20), "authorIs" varchar(20), "checkResultId" varchar(20), "premiseActionId" varchar, "premiseConfigHash" varchar(300), CONSTRAINT "REL_1a63301452c394f67093b473b2" UNIQUE ("itemIs"), CONSTRAINT "REL_1b857d089dc67957193851c7a6" UNIQUE ("authorIs"))`);
        await queryRunner.query(`INSERT INTO "ActionResult"("id", "createdAt", "run", "dryRun", "success", "runReason", "result", "itemIs", "authorIs", "checkResultId", "premiseActionId", "premiseConfigHash") SELECT "id", "createdAt", "run", "dryRun", "success", "runReason", "result", "itemIs", "authorIs", "checkResultId", "premiseActionId", "premiseConfigHash" FROM "temporary_ActionResult"`);
        await queryRunner.query(`DROP TABLE "temporary_ActionResult"`);
        await queryRunner.query(`ALTER TABLE "ActionPremise" RENAME TO "temporary_ActionPremise"`);
        await queryRunner.query(`CREATE TABLE "ActionPremise" ("actionId" varchar NOT NULL, "config" text NOT NULL, "configHash" varchar(300) NOT NULL, "version" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), PRIMARY KEY ("actionId", "configHash"))`);
        await queryRunner.query(`INSERT INTO "ActionPremise"("actionId", "config", "configHash", "version", "createdAt", "updatedAt") SELECT "actionId", "config", "configHash", "version", "createdAt", "updatedAt" FROM "temporary_ActionPremise"`);
        await queryRunner.query(`DROP TABLE "temporary_ActionPremise"`);
        await queryRunner.query(`ALTER TABLE "RuleResult" RENAME TO "temporary_RuleResult"`);
        await queryRunner.query(`CREATE TABLE "RuleResult" ("id" varchar(20) PRIMARY KEY NOT NULL, "createdAt" integer NOT NULL, "triggered" boolean, "result" text, "fromCache" boolean, "data" text, "premiseRuleId" varchar, "premiseConfigHash" varchar(300), "checkResultId" varchar(20), "itemIs" varchar(20), "authorIs" varchar(20), CONSTRAINT "REL_d7fcca9682f7bcbb351f52f1b8" UNIQUE ("itemIs"), CONSTRAINT "REL_6663c0489c4b25c87e10695197" UNIQUE ("authorIs"))`);
        await queryRunner.query(`INSERT INTO "RuleResult"("id", "createdAt", "triggered", "result", "fromCache", "data", "premiseRuleId", "premiseConfigHash", "checkResultId", "itemIs", "authorIs") SELECT "id", "createdAt", "triggered", "result", "fromCache", "data", "premiseRuleId", "premiseConfigHash", "checkResultId", "itemIs", "authorIs" FROM "temporary_RuleResult"`);
        await queryRunner.query(`DROP TABLE "temporary_RuleResult"`);
        await queryRunner.query(`ALTER TABLE "RulePremise" RENAME TO "temporary_RulePremise"`);
        await queryRunner.query(`CREATE TABLE "RulePremise" ("ruleId" varchar NOT NULL, "configHash" varchar(300) NOT NULL, "config" text NOT NULL, "version" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), PRIMARY KEY ("ruleId", "configHash"))`);
        await queryRunner.query(`INSERT INTO "RulePremise"("ruleId", "configHash", "config", "version", "createdAt", "updatedAt") SELECT "ruleId", "configHash", "config", "version", "createdAt", "updatedAt" FROM "temporary_RulePremise"`);
        await queryRunner.query(`DROP TABLE "temporary_RulePremise"`);
        await queryRunner.query(`ALTER TABLE "Rule" RENAME TO "temporary_Rule"`);
        await queryRunner.query(`CREATE TABLE "Rule" ("id" varchar(300) PRIMARY KEY NOT NULL, "name" varchar(300), "kindId" integer, "managerId" varchar(20))`);
        await queryRunner.query(`INSERT INTO "Rule"("id", "name", "kindId", "managerId") SELECT "id", "name", "kindId", "managerId" FROM "temporary_Rule"`);
        await queryRunner.query(`DROP TABLE "temporary_Rule"`);
        await queryRunner.query(`DROP INDEX "IDX_4cec0381d1eb9dedaf3ad68b56"`);
        await queryRunner.query(`ALTER TABLE "FilterCriteriaResult" RENAME TO "temporary_FilterCriteriaResult"`);
        await queryRunner.query(`CREATE TABLE "FilterCriteriaResult" ("id" varchar(20) PRIMARY KEY NOT NULL, "behavior" varchar(20) NOT NULL, "propertyResults" text NOT NULL, "passed" boolean NOT NULL, "type" varchar NOT NULL, "filterResultId" varchar(20), "criteriaId" varchar(20))`);
        await queryRunner.query(`INSERT INTO "FilterCriteriaResult"("id", "behavior", "propertyResults", "passed", "type", "filterResultId", "criteriaId") SELECT "id", "behavior", "propertyResults", "passed", "type", "filterResultId", "criteriaId" FROM "temporary_FilterCriteriaResult"`);
        await queryRunner.query(`DROP TABLE "temporary_FilterCriteriaResult"`);
        await queryRunner.query(`CREATE INDEX "IDX_4cec0381d1eb9dedaf3ad68b56" ON "FilterCriteriaResult" ("type") `);
        await queryRunner.query(`DROP INDEX "IDX_99faa3b1f539a14f095192a127"`);
        await queryRunner.query(`DROP TABLE "TotalStat"`);
        await queryRunner.query(`DROP INDEX "IDX_842bf2abc463b163fdd4406031"`);
        await queryRunner.query(`DROP TABLE "TimeSeriesStat"`);
        await queryRunner.query(`DROP TABLE "DispatchedAction"`);
        await queryRunner.query(`DROP TABLE "Action"`);
        await queryRunner.query(`DROP TABLE "Manager"`);
        await queryRunner.query(`DROP TABLE "Bot"`);
        await queryRunner.query(`DROP INDEX "IDX_006cd1e68c2aac42e763dba332"`);
        await queryRunner.query(`DROP TABLE "Subreddit"`);
        await queryRunner.query(`DROP INDEX "IDX_fab3ccdf4e40a98708e2fa7380"`);
        await queryRunner.query(`DROP INDEX "IDX_299b1e2f9643fd7670370b726f"`);
        await queryRunner.query(`DROP TABLE "Activity"`);
        await queryRunner.query(`DROP INDEX "IDX_04380a477fa96ef4f0935a1224"`);
        await queryRunner.query(`DROP INDEX "IDX_1a2b070b8e5a31b4e041338645"`);
        await queryRunner.query(`DROP TABLE "CMEvent"`);
        await queryRunner.query(`DROP TABLE "ActivitySource"`);
        await queryRunner.query(`DROP TABLE "RunResult"`);
        await queryRunner.query(`DROP TABLE "Run"`);
        await queryRunner.query(`DROP TABLE "Check"`);
        await queryRunner.query(`DROP TABLE "CheckResult"`);
        await queryRunner.query(`DROP TABLE "ActionResult"`);
        await queryRunner.query(`DROP TABLE "ActionPremise"`);
        await queryRunner.query(`DROP TABLE "RuleResult"`);
        await queryRunner.query(`DROP TABLE "RulePremise"`);
        await queryRunner.query(`DROP TABLE "Rule"`);
        await queryRunner.query(`DROP TABLE "RuleType"`);
        await queryRunner.query(`DROP INDEX "IDX_62bbc6b414a9b54b8c16cbaf72"`);
        await queryRunner.query(`DROP TABLE "FilterCriteria"`);
        await queryRunner.query(`DROP INDEX "IDX_4cec0381d1eb9dedaf3ad68b56"`);
        await queryRunner.query(`DROP TABLE "FilterCriteriaResult"`);
        await queryRunner.query(`DROP INDEX "IDX_d859426c8ed19b1a6a89c2a3e8"`);
        await queryRunner.query(`DROP TABLE "FilterResult"`);
        await queryRunner.query(`DROP TABLE "Author"`);
        await queryRunner.query(`DROP TABLE "ActionType"`);
    }

}
